output_dir: ~/scratch/experiments/

dataset:
  class: FB15k237LogicalQuery
  path: ~/kg-datasets/

task:
  class: LogicalQuery
  model:
    class: GNN-QE
    model:
      class: NBFNet
      input_dim: 32
      hidden_dims: [32, 32, 32, 32]
      message_func: distmult
      aggregate_func: pna
      short_cut: yes
      layer_norm: yes
      dependent: yes
    logic: product
    dropout_ratio: 0.25
  criterion: bce
  sample_weight: no
  adversarial_temperature: 0.2
  noise_level: .5
  adversarial_strength: 0.5
  perturb_target: '' # linear # see PerturbTarget,
  mutual_info_weighted_perturb: False

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 2

train:
  num_epoch: 10
  batch_per_epoch: 1000

metric: mrr

evaluate:
  checkpoint: ~/projects/graph_neural_network_query_executor/models/model_original/model_epoch_10.pth
  attack_method: soft_edge_pgd
  attack_scale: 0.02 # 0.4
  pgd_eps: 3
  pgd_steps: 3
  edge_ratio: 0.05