output_dir: ~/scratch/experiments/

dataset:
  class: NELL995LogicalQuery
  path: ~/kg-datasets/

task:
  class: LogicalQuery
  model:
    class: GNN-QE
    model:
      class: NBFNet
      input_dim: 32
      hidden_dims: [32, 32, 32, 32]
      message_func: distmult
      aggregate_func: pna
      short_cut: yes
      layer_norm: yes
      concat_hidden: yes
      dependent: yes
    logic: product
    dropout_ratio: 0.25
  criterion: bce
  sample_weight: yes
  adversarial_temperature: 0.2
  adversarial_strength: 0.5
  perturb_target: soft_edge_pgd # linear # see PerturbTarget,
  mutual_info_weighted_perturb: False
  noise_level: .4
  pgd_eps: 1
  pgd_steps: 3
  edge_ratio: 0.05

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 8

train:
  num_epoch: 10
  batch_per_epoch: 3000

metric: mrr

evaluate: ""
#  checkpoint: ~/projects/graph_neural_network_query_executor/models/model_original/model_epoch_10.pth
#  attack_method: relation_emb_pgd #soft_edge_pgd
#  attack_scale: 0.4
#  pgd_eps: 3
#  pgd_steps: 5
#  edge_ratio: 0.05